version: '3'

services:
  chamapp-db:
    image: bitnami/postgresql:latest
    container_name: chamapp-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=chamapp
    volumes:
      - chamapp_pg_data:/bitnami/postgresql

volumes:
  chamapp_pg_data:
